#!/bin/bash -eu

echo "Offline test.  This should go fast."

root=$(cd $(dirname "$0")/.. && pwd)
cd $root


ginkgo \
  -p -r \
  --randomizeAllSpecs \
  --randomizeSuites \
  -skipPackage acceptance,aws_enemy,integration

ginkgo \
  -p -r \
  --randomizeAllSpecs \
  --randomizeSuites \
  ./integration
