#!/bin/bash -eu

root=$(cd $(dirname "$0")/.. && pwd)
cd $root

ginkgo \
  -p -r \
  --randomizeAllSpecs \
  --randomizeSuites \
  -skipPackage acceptance,aws_enemy,integration

ginkgo \
  -p -r \
  --randomizeAllSpecs \
  --randomizeSuites \
  ./integration
